import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

// Register topics
import './topics/linked-list/index'
import './topics/stack/index'
import './topics/binary-tree/index'
import './topics/hash-table/index'
import './topics/heap/index'
import './topics/recursion/index'
import './topics/graph/index'
import './topics/sorting/index'
import './topics/shortest-path/index'
import './topics/binary-search/index'
import './topics/string-matching/index'
import './topics/union-find/index'
import './topics/dynamic-programming/index'
import './topics/sliding-window/index'
import './topics/backtracking/index'
import './topics/topological-sort/index'
import './topics/greedy/index'
import './topics/two-pointers/index'
import './topics/prefix-sum/index'
import './topics/difference-array/index'
import './topics/monotonic-stack/index'
import './topics/monotonic-queue/index'
import './topics/trie/index'
import './topics/bit-manipulation/index'
import './topics/segment-tree/index'
import './topics/fenwick-tree/index'
import './topics/mst/index'
import './topics/memoization/index'
import './topics/b-tree/index'
import './topics/non-comparison-sort/index'
import './topics/skip-list/index'
import './topics/bloom-filter/index'
import './topics/floyd-warshall/index'
import './topics/avl-tree/index'
import './topics/red-black-tree/index'
import './topics/string-hashing/index'
import './topics/bellman-ford/index'
import './topics/max-flow/index'
import './topics/bipartite-graph/index'
import './topics/knapsack/index'
import './topics/lru-cache/index'
import './topics/suffix-array/index'
import './topics/astar-search/index'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
