import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

// Register topics
import './topics/linked-list/index'
import './topics/stack/index'
import './topics/binary-tree/index'
import './topics/hash-table/index'
import './topics/heap/index'
import './topics/recursion/index'
import './topics/graph/index'
import './topics/sorting/index'
import './topics/shortest-path/index'
import './topics/binary-search/index'
import './topics/string-matching/index'
import './topics/union-find/index'
import './topics/dynamic-programming/index'
import './topics/sliding-window/index'
import './topics/backtracking/index'
import './topics/topological-sort/index'
import './topics/greedy/index'
import './topics/two-pointers/index'
import './topics/prefix-sum/index'
import './topics/difference-array/index'
import './topics/monotonic-stack/index'
import './topics/monotonic-queue/index'
import './topics/trie/index'
import './topics/bit-manipulation/index'
import './topics/segment-tree/index'
import './topics/fenwick-tree/index'
import './topics/mst/index'
import './topics/memoization/index'
import './topics/b-tree/index'
import './topics/non-comparison-sort/index'
import './topics/skip-list/index'
import './topics/bloom-filter/index'
import './topics/floyd-warshall/index'
import './topics/avl-tree/index'
import './topics/red-black-tree/index'
import './topics/string-hashing/index'
import './topics/bellman-ford/index'
import './topics/max-flow/index'
import './topics/bipartite-graph/index'
import './topics/knapsack/index'
import './topics/lru-cache/index'
import './topics/suffix-array/index'
import './topics/astar-search/index'
import './topics/eulerian-path/index'
import './topics/binary-search-answer/index'
import './topics/min-cost-max-flow/index'
import './topics/aho-corasick/index'
import './topics/splay-tree/index'
import './topics/treap/index'
import './topics/suffix-tree/index'
import './topics/z-algorithm/index'
import './topics/strongly-connected-components/index'
import './topics/prefix-function/index'
import './topics/manacher/index'
import './topics/2-sat/index'
import './topics/bridges-and-articulation/index'
import './topics/cartesian-tree/index'
import './topics/heavy-light-decomposition/index'
import './topics/dinic/index'
import './topics/sieve-of-eratosthenes/index'
import './topics/extended-gcd/index'
import './topics/link-cut-tree/index'
import './topics/palindromic-tree/index'
import './topics/euler-totient/index'
import './topics/centroid-decomposition/index'
import './topics/lyndon-factorization/index'
import './topics/mos-algorithm/index'
import './topics/inclusion-exclusion/index'
import './topics/push-relabel/index'
import './topics/persistent-segment-tree/index'
import './topics/randomized-algorithm/index'
import './topics/amortized-analysis/index'
import './topics/sparse-table/index'
import './topics/chinese-remainder-theorem/index'
import './topics/kmp-automaton/index'
import './topics/matrix-exponentiation/index'
import './topics/miller-rabin/index'
import './topics/fenwick-range/index'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
